feat: Renaming `master` to `main` wherever it's referenced
gruntwork-io/terratest pull request #1476
Opened 2024-12-02 15:45 UTC by yhakbar

## Description

Fixes #1473.

Right before merging this, we'll need to explicitly perform the rename of the default branch from `master` to `main` in the GitHub repository settings.

This will ensure that all PRs get moved over to the new branch name, etc.

## TODOs

Read the [Gruntwork contribution guidelines](https://gruntwork.notion.site/Gruntwork-Coding-Methodology-02fdcd6e4b004e818553684760bf691e).

- [x] Update the docs.
- [x] Run the relevant tests successfully, including pre-commit checks.
- [x] Ensure any 3rd party code adheres with our [license policy](https://www.notion.so/gruntwork/Gruntwork-licenses-and-open-source-usage-policy-f7dece1f780341c7b69c1763f22b1378) or delete this line if its not applicable.
- [x] Include release notes. If this PR is backward incompatible, include a migration guide.

## Release Notes (draft)

Updated default branch from `master` to `main`.

### Migration Guide

If you have a locally cloned copy of Terratest, make sure to delete the `master` branch and check out the `main` branch.

2024-12-03 02:46 UTC, james03160927 approved these changes
LGTM

2024-12-03 02:50 UTC, james03160927 requested changes
It seems like this change is breaking some unit tests. 
* TestGitRefChecks/GetCurrentBranchNameReturnsBranchName
* TestGitRefChecks/GetCurrentBranchNameReturnsBranchName

Other failing tests don't seem to be related.

2024-12-03 03:29 UTC, yhakbar commented
> It seems like this change is breaking some unit tests. 
> * TestGitRefChecks/GetCurrentBranchNameReturnsBranchName
> * TestGitRefChecks/GetCurrentBranchNameReturnsBranchName
> 
> Other failing tests don't seem to be related. 

It seemed to me like the root cause of those failures was in itself the change in branch name. Is that assessment wrong?

2024-12-03 13:01 UTC, yhakbar commented
If I'm not being clear, this line:
https://github.com/gruntwork-io/terratest/pull/1476/files#diff-61142d541db9ae6c5a711f72f57cf7c1c312cda26bf0e9a6d8d09e6188e83f11L32-R32

Won't work right now because the `main` branch doesn't exist. Once we rename `master` to `main`, it should.

2024-12-04 01:55 UTC, james03160927 commented
> If I'm not being clear, this line: https://github.com/gruntwork-io/terratest/pull/1476/files#diff-61142d541db9ae6c5a711f72f57cf7c1c312cda26bf0e9a6d8d09e6188e83f11L32-R32
> 
> Won't work right now because the `main` branch doesn't exist. Once we rename `master` to `main`, it should.



> If I'm not being clear, this line: https://github.com/gruntwork-io/terratest/pull/1476/files#diff-61142d541db9ae6c5a711f72f57cf7c1c312cda26bf0e9a6d8d09e6188e83f11L32-R32
> 
> Won't work right now because the `main` branch doesn't exist. Once we rename `master` to `main`, it should.

Ah you are right. LGTM then!

2024-12-04 01:56 UTC, james03160927 approved these changes
LGTM

2024-12-04 01:56 UTC, merged