[Azure] Add sovereign cloud support for log analytics
gruntwork-io/terratest pull request #857
Opened 2021-04-08 14:35 UTC by davidkpiano

This PR resolves the Base URI for the monitor module to support sovereign cloud.

Addresses #811, fixes #856

cc. @rguthriemsft

2021-04-08 18:38 UTC, hattan commented
[Microsoft CI Bot] TL;DR; success :thumbsup:

You can check the status of the CI Pipeline logs here ; https://github.com/aztfmod/terratest/actions/runs/730443366

2021-04-26 16:53 UTC, HadwaAbdelhalem requested changes
Thanks @davidkpiano , Mostly LGTM please cleanup the merge conflicts comments

2021-04-26 16:53 UTC, HadwaAbdelhalem commented on modules/azure/client_factory.go
> +=======
@davidkpiano , please cleanup the merge conflicts comments

2021-04-26 16:53 UTC, HadwaAbdelhalem commented on modules/azure/client_factory.go
please cleanup the merge conflicts comments

2021-04-30 18:27 UTC, davidkpiano commented
Superseded by #884

2021-04-30 18:27 UTC, closed without merging