[Azure] Add sovereign cloud support for MySQL
gruntwork-io/terratest pull request #862
Opened 2021-04-08 14:54 UTC by davidkpiano

This PR resolves the Base URI for the MySQL module to support sovereign cloud.

Addresses #811, fixes #858 

cc. @rguthriemsft

2021-04-08 18:39 UTC, hattan commented
[Microsoft CI Bot] TL;DR; success :thumbsup:

You can check the status of the CI Pipeline logs here ; https://github.com/aztfmod/terratest/actions/runs/730444481

2021-04-16 19:15 UTC, HadwaAbdelhalem requested changes
Mostly LGTM. One minor NIT change

2021-04-16 20:37 UTC, HadwaAbdelhalem commented on modules/azure/mysql.go
> +// TODO: remove in next version
please ignore this comment, as per another conversation https://github.com/gruntwork-io/terratest/pull/868#discussion_r615078590 , all methods would be removed in one final PR for backward compatibility

2021-04-20 20:17 UTC, hattan commented
[Microsoft CI Bot] TL;DR; success :thumbsup:

You can check the status of the CI Pipeline logs here ; https://github.com/aztfmod/terratest/actions/runs/768301876

2021-04-26 16:49 UTC, HadwaAbdelhalem approved these changes
LGTM, @gruntwork-io/gruntwork-terratest-terragrunt ready for your review

2021-04-29 17:36 UTC, yorinasub17 commented
NOTE: Looks like there is a merge conflict now that we merged some of the other PRs.

2021-04-30 18:27 UTC, davidkpiano commented
Superseded by #884

2021-04-30 18:27 UTC, closed without merging